# WrenAI NLP Core 配置示例
# 复制此文件为 config.yaml 并根据需要修改配置

# LLM配置
llm:
  # 模型类型：openai, glm
  provider: "openai"
  
  # 模型名称
  # OpenAI: "gpt-3.5-turbo", "gpt-4" 等
  # GLM: "glm-4", "glm-3-turbo" 等
  model: "gpt-3.5-turbo"
  
  # API密钥
  api_key: "your-api-key-here"
  
  # API基础URL（可选，用于自定义端点）
  # OpenAI: "https://api.openai.com/v1"
  # GLM: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
  base_url: null
  
  # 生成参数
  temperature: 0.1  # 生成温度，控制随机性
  max_tokens: 1000  # 最大生成token数
  context_window_size: 4096  # 上下文窗口大小

# 核心引擎配置
core:
  # 是否启用意图分类
  enable_intent_classification: true
  
  # 是否启用SQL生成推理
  enable_sql_generation_reasoning: false
  
  # 最大历史对话数量
  max_histories: 5
  
  # 日志级别
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# 环境变量配置示例：
# 也可以通过以下环境变量来配置：
# 
# WREN_LLM_MODEL=gpt-3.5-turbo
# WREN_LLM_API_KEY=your-api-key
# WREN_LLM_BASE_URL=https://api.openai.com/v1
# WREN_LLM_TEMPERATURE=0.1
# WREN_LLM_MAX_TOKENS=1000
# WREN_LLM_CONTEXT_WINDOW=4096
# WREN_ENABLE_INTENT_CLASSIFICATION=true
# WREN_ENABLE_SQL_REASONING=false
# WREN_MAX_HISTORIES=5
# WREN_LOG_LEVEL=INFO